name: Deploy to Heroku for Tictactoe

on:
 push:
  branches: [master]
  
  
jobs:
 build-deploy-heroku-tictactoe:
  runs-on: ubuntu-latest
  steps:
   - name : Checkout
     uses : actions/checkout@v2
     
   - name : Set up JDK 11
     uses : actions/setup-java@v2
     with:
      java-version : '11'
      distribution : 'adopt'
      
   - name : Build with Maven
     run : mvn clean install -DskipTests
     
   - name : Build, Push and Release a docker container to Heroku.
     uses : gonuit/heroku-docker-deploy@v1.3.3
     with:
     
      email : ${{ secrets.HEROKU_EMAIL }}
      heroku_api_key : ${{ secrets.HEROKU_API_KEY }}
      
      heroku_app_name : ${{ secrets.HEROKU_APP_NAME }}
      
      dockerfile_directory : ./
      
      dockerfile_name : Dockerfile
      
      docker_options : "--no-cache"
      
      process_type : web
